export const dataAbout = {
  image: '/images/barcelona.png',
  title: 'Барселона — обзор города',
  text: `Барселона с её золотистыми пляжами, архитектурными шедеврами Гауди, многочисленными фестивалями и гастрономическим разнообразием понравилась мне в первый же день пребывания и стала местом, в котором...`,
};

export const dataReviews = [
  {
    authorImg: '/images/user1.png',
    authorName: 'Наталия Полянская',
    town: 'БАРСЕЛОНА',
    review: `Барселона – моя третья большая любовь, после Вены и Крита. Это город, в который я каждый раз возвращаюсь с огромным удовольствием, всем рекомендую хоть раз там побывать и осмотреть ...`,
    images: [
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
    ],
    date: 'около 1 года назад',
    comments: '9 комментариев',
    likes: 9,
  },
  {
    authorImg: '/images/user1.png',
    authorName: 'Elena Bulgakova',
    town: 'БАРСЕЛОНА',
    review: `Плюсы города: весь город одни плюсы! Минусы города: не видела. В наш марафон по Европе не вписалось 2 испанских города от усталости - решили остаток путешествия провести в Барселоне ...`,
    images: [
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
    ],
    date: '5 месяцев назад',
    comments: '3 комментария',
    likes: 7,
  },
  {
    authorImg: '/images/user1.png',
    authorName: 'Наталия Полянская',
    town: 'БАРСЕЛОНА',
    review: `Барселона – моя третья большая любовь, после Вены и Крита. Это город, в который я каждый раз возвращаюсь с огромным удовольствием, всем рекомендую хоть раз там побывать и осмотреть ...`,
    images: [
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
    ],
    date: 'около 1 года назад',
    comments: '9 комментариев',
    likes: 9,
  },
  {
    authorImg: '/images/user1.png',
    authorName: 'Elena Bulgakova',
    town: 'БАРСЕЛОНА',
    review: `Плюсы города: весь город одни плюсы! Минусы города: не видела. В наш марафон по Европе не вписалось 2 испанских города от усталости - решили остаток путешествия провести в Барселоне ...`,
    images: [
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
    ],
    date: '5 месяцев назад',
    comments: '3 комментария',
    likes: 7,
  },
  {
    authorImg: '/images/user1.png',
    authorName: 'Наталия Полянская',
    town: 'БАРСЕЛОНА',
    review: `Барселона – моя третья большая любовь, после Вены и Крита. Это город, в который я каждый раз возвращаюсь с огромным удовольствием, всем рекомендую хоть раз там побывать и осмотреть ...`,
    images: [
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
    ],
    date: 'около 1 года назад',
    comments: '9 комментариев',
    likes: 9,
  },
  {
    authorImg: '/images/user1.png',
    authorName: 'Elena Bulgakova',
    town: 'БАРСЕЛОНА',
    review: `Плюсы города: весь город одни плюсы! Минусы города: не видела. В наш марафон по Европе не вписалось 2 испанских города от усталости - решили остаток путешествия провести в Барселоне ...`,
    images: [
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
    ],
    date: '5 месяцев назад',
    comments: '3 комментария',
    likes: 7,
  },
  {
    authorImg: '/images/user1.png',
    authorName: 'Наталия Полянская',
    town: 'БАРСЕЛОНА',
    review: `Барселона – моя третья большая любовь, после Вены и Крита. Это город, в который я каждый раз возвращаюсь с огромным удовольствием, всем рекомендую хоть раз там побывать и осмотреть ...`,
    images: [
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
    ],
    date: 'около 1 года назад',
    comments: '9 комментариев',
    likes: 9,
  },
  {
    authorImg: '/images/user1.png',
    authorName: 'Elena Bulgakova',
    town: 'БАРСЕЛОНА',
    review: `Плюсы города: весь город одни плюсы! Минусы города: не видела. В наш марафон по Европе не вписалось 2 испанских города от усталости - решили остаток путешествия провести в Барселоне ...`,
    images: [
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
    ],
    date: '5 месяцев назад',
    comments: '3 комментария',
    likes: 7,
  },
  {
    authorImg: '/images/user1.png',
    authorName: 'Наталия Полянская',
    town: 'БАРСЕЛОНА',
    review: `Барселона – моя третья большая любовь, после Вены и Крита. Это город, в который я каждый раз возвращаюсь с огромным удовольствием, всем рекомендую хоть раз там побывать и осмотреть ...`,
    images: [
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
    ],
    date: 'около 1 года назад',
    comments: '9 комментариев',
    likes: 9,
  },
  {
    authorImg: '/images/user1.png',
    authorName: 'Elena Bulgakova',
    town: 'БАРСЕЛОНА',
    review: `Плюсы города: весь город одни плюсы! Минусы города: не видела. В наш марафон по Европе не вписалось 2 испанских города от усталости - решили остаток путешествия провести в Барселоне ...`,
    images: [
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
    ],
    date: '5 месяцев назад',
    comments: '3 комментария',
    likes: 7,
  },
  {
    authorImg: '/images/user1.png',
    authorName: 'Наталия Полянская',
    town: 'БАРСЕЛОНА',
    review: `Барселона – моя третья большая любовь, после Вены и Крита. Это город, в который я каждый раз возвращаюсь с огромным удовольствием, всем рекомендую хоть раз там побывать и осмотреть ...`,
    images: [
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
    ],
    date: 'около 1 года назад',
    comments: '9 комментариев',
    likes: 9,
  },
  {
    authorImg: '/images/user1.png',
    authorName: 'Elena Bulgakova',
    town: 'БАРСЕЛОНА',
    review: `Плюсы города: весь город одни плюсы! Минусы города: не видела. В наш марафон по Европе не вписалось 2 испанских города от усталости - решили остаток путешествия провести в Барселоне ...`,
    images: [
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
    ],
    date: '5 месяцев назад',
    comments: '3 комментария',
    likes: 7,
  },
  {
    authorImg: '/images/user1.png',
    authorName: 'Наталия Полянская',
    town: 'БАРСЕЛОНА',
    review: `Барселона – моя третья большая любовь, после Вены и Крита. Это город, в который я каждый раз возвращаюсь с огромным удовольствием, всем рекомендую хоть раз там побывать и осмотреть ...`,
    images: [
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
    ],
    date: 'около 1 года назад',
    comments: '9 комментариев',
    likes: 9,
  },
  {
    authorImg: '/images/user1.png',
    authorName: 'Elena Bulgakova',
    town: 'БАРСЕЛОНА',
    review: `Плюсы города: весь город одни плюсы! Минусы города: не видела. В наш марафон по Европе не вписалось 2 испанских города от усталости - решили остаток путешествия провести в Барселоне ...`,
    images: [
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
      '/images/review1.png',
      '/images/review2.png',
      '/images/review3.png',
    ],
    date: '5 месяцев назад',
    comments: '3 комментария',
    likes: 7,
  },
];

export const dataChatUsers = {
  admin: {
    name: 'Администратор',
    img: '/images/user1.png',
    position: 'TravelAsk',
  },
  user: {
    name: 'Наталия Полянская',
    img: '/images/user2.png',
    position: 'Гид по Баварии, фотограф',
  },
};

export const dataChatMessages = [
  {
    sender: 'admin',
    message: `Из достопримечательностей могу предложить обратить внимание на вулкан Майон, путешествие запомнится вам надолго хотя бы из-за невероятной сложности подъема на него. Поверьте, это стоит того; также хотелf бы отметить очень важную область исследования`,
    date: 'Вчера в 17:45',
  },
  {
    sender: 'user',
    message: `Что из себя представляет вулкан? Просто хочу убедиться, что готова к такому путешествию.`,
    date: 'Вчера в 18:45',
  },
  {
    sender: 'admin',
    message: `Из достопримечательностей могу предложить обратить внимание на вулкан Майон, путешествие запомнится вам надолго хотя бы из-за невероятной сложности подъема на него. Поверьте, это стоит того; также хотелf бы отметить очень важную область исследования`,
    date: 'Вчера в 17:45',
  },
];
